### ISSUE TITLE
Apply for verified badge?

### ISSUE THREAD

**Issue by MessiasLima** [git-town/action#40]
Some companies can only use actions from verified owners. Is it possible for you to get the verified badge?

https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by tranhl** [comment]
Good callout, thanks for raising this! @kevgo I'll need your help sorting this out 🙏

**Comment by kevgo** [comment]
Thanks for reaching out about this. I have followed the steps in the linked document and added all missing information for the organization. However, when I try to get the publisher verification, I'm getting the message below rather than the checklist. Looks like the publisher verification applies only to GitHub/OAuth Apps, not to published Actions?

![image](https://github.com/user-attachments/assets/ec4d1b5e-7902-4f68-bb1c-9ab26848ce39)

**Comment by MessiasLima** [comment]
Look like GitHub naming is a bit misleading.

Published verification is not for Actions. This link shows a case of an organisation that has the published verification but does not have the actions verified. It can be useful anyway

https://github.com/orgs/community/discussions/25265

**Comment by kevgo** [comment]
It looks like the `readmeio` organization is verified because they have a [GitHub App](https://github.com/marketplace/readme-micro). Since the `git-town` organization doesn’t have such an app, there doesn't seem to be a way for it to be verified at the moment. I definitely agree that it would be a useful feature&mdash;hopefully GitHub will consider expanding verification options in the future. Appreciate the links you shared, it was interesting to learn about GitHub verification options!
